### ISSUE TITLE
Permission denied while trying to convert any file

### ISSUE THREAD

**Issue by sbritorodr** [AbhiralJain/FFmpeg#2]
The device I'm having this issue is running Android 11 and the app is at version 1.1.9

Steps to reproduce: take any file and do any process using the file and will give an error "opperation not permitted" the file permissions are allowed for this app, but only for multimedia. 

Hints for the solution: either ask android to have permissions to r/w all storage or change default output folder to any for multimedia.

**Comment by AbhiralJain** [comment]
This happens when the the format of the output file is neither a video or audio. Android doesn't allow other files to be written in external directory.
